
my:
  name: 万俊义的儿子
  gender: boy
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/1911?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 6000ms
    jedis:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud: 
    bus:
      enabled: true
      trace: 
        enabled: true
  zipkin:
    base-url: http://localhost:9411
        
management:
  endpoints: 
    web: 
      exposure: 
        include: "*"